# Generated by Django 2.1.1 on 2018-09-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='picture',
            field=models.ImageField(default='/static/assets/placeholder.png', upload_to='media'),
        ),
    ]
