# Generated by Django 2.1.1 on 2018-09-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20180911_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
