# Generated by Django 2.1.1 on 2018-09-22 02:38

import art.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_auto_20180922_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(default='/static/assets/placeholder.png', upload_to=art.models.user_directory_path),
        ),
    ]
