# Generated by Django 2.1.1 on 2018-09-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_auto_20180925_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='taking_request',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
