# Generated by Django 2.1.1 on 2018-09-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_auto_20180925_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='taking_request',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
